### ISSUE TITLE
Failed to install uploaded module : Module zfsmanager does not support this operating system (Sun Solaris 11)

### ISSUE THREAD

**Issue by averyfreeman** [jonmatifa/zfsmanager#16]
Hi, 

thanks so much for creating this module.  I've used it with other operating systems and have decided to use Solaris 11.3 for an ESXi NFS datastore.  Unfortunately, when I tried to install the ZFS module (which I love), I got this:

`Failed to install uploaded module : Module zfsmanager does not support this operating system (Sun Solaris 11)`

This looks like it'd be something that would be easy to fix - is there any way you could tell me where to change it so it's accepted?

Thank you,
Avery

**Comment by jonmatifa** [comment]
Look in module.info for the line that reads "os_support=*-linux freebsd" I believe you could just remove that line entirely, add a * to it or simply add the OS name to it. I'm not sure what webmin shows as the OS name for Solaris as their API documentation website is down at the moment.

**Comment by averyfreeman** [comment]
Ah, yes I tried that but it didn't work.  

I used Solaris for a couple months before I got tired of its non-progressive userland and ditched it for ZOL.  Thank you though!  Likely no-one else will ask since it's practically dead, unfortunately.
