### ISSUE TITLE
Spelling error on aclinherit property

### ISSUE THREAD

**Issue by BadWolf43** [jonmatifa/zfsmanager#17]
Attempting to set zfs property aclinherit to pasthrough on dpool/Movies with command... 
zfs set aclinherit=**pasthrough** dpool/Files

error: cannot set property for 'dpool/Files': 'aclinherit' must be one of 'discard | noallow | restricted | **passthrough** | passthrough-x' 

![spellingerror](https://user-images.githubusercontent.com/34453632/33843220-bfa7c406-de6a-11e7-80ef-4e3f35a3c496.jpg)

**Comment by jonmatifa** [comment]
See above, I just tested this and it should be working now.
