### ISSUE TITLE
Support for pool version 5000

### ISSUE THREAD

**Issue by vinnie-ki** [jonmatifa/zfsmanager#18]
The supported poolversions now only go up to 28. Pool version 5000 is around some time now. How about supporting it in zfsmanger?

**Comment by jonmatifa** [comment]
Pool version 5000 corresponds to the Feature Flags implementation in OpenZFS, which is supported. You can specify a legacy pool version upon creation for backwards compatibility, or omit the option which will automatically create a pool supporting the latest Feature Flags.
