### ISSUE TITLE
Cant install Modul on Webmin 

### ISSUE THREAD

**Issue by boospy** [jonmatifa/zfsmanager#22]
Hello, 

this day i would test this interface hiere on Proxmox5.1 with Webmin 1.870. But it didn't work. When i install the ... i get this error-message:

> Failed to install uploaded module : Module lang is missing a module.info file
What i have to do that the installation is working?

Thanks a lot and best Regards

**Comment by jonmatifa** [comment]
boospy,

I believe I made a mistake when I crafted the v0.1.5 release, v0.1.5a is now available. I'll attach it to this comment as well.
[zfsmanager-0.1.5.wbm.gz](https://github.com/jonmatifa/zfsmanager/files/1653456/zfsmanager-0.1.5.wbm.gz)

**Comment by boospy** [comment]
Thank you for your answer :) i will test it!

**Comment by boospy** [comment]
It is working now! Thanks for the fast fix :+1:
