### ISSUE TITLE
Great Project, love it :)

### ISSUE THREAD

**Issue by datenheim** [jonmatifa/zfsmanager#6]
Hello,
today I just want to let you know: this project is great and fills a major gap in webmin.
Although it is in early state it´s quite useful and has more functions than I expected.
So far I tested all "read only" functions and the results look promising, familiar and correct.
Deleting snapshots also worked well. Will test it on more machines within the next time.
Is there anything one can do to bring this module forward?
Anyway - I like it very much and will stick to it from  now on.
Best regards, Stefan

**Comment by jonmatifa** [comment]
Hello and thank you for your feedback and am glad to hear that you're using it! I think just having some feedback would be most helpful, which features you like, which ones are missing, in what environment you are using this in, etc. and of course, bugs.

If you have an interest in the coding side of things, let me know. I want to do some major overhauling before I add too many new features.

Cheers,
Marc

**Comment by kaudley** [comment]
This is awesome!!  This could actually be one of the only really usable "gui" management tools for ZoL - I'm putting it through the paces on my home Ubuntu 14.04 media servers, so far it's excellent and I've had no issues.  Great Work!

**Comment by dannyb78** [comment]
nice job jonmatifa. I just installed your script on a test env. It seems to works fine.
hope you'll develop more functions, like disk replacement and pools management :+1:
