### ISSUE TITLE
Missing file to read at zfsmanager::./zfsmanager-lib.pl line 41

### ISSUE THREAD

**Issue by jaimerojast** [jonmatifa/zfsmanager#9]
when i install the zfsmanager in webmin shows me this error:

`Missing file to read at zfsmanager::./zfsmanager-lib.pl line 41`

am using the version 1.791 of webmin in ubuntu 14

thnks for you project.

regards.

Jaime.

**Comment by mcwago** [comment]
me too

**Comment by jonmatifa** [comment]
It may be missing /etc/webmin/zfsmanager/config in which case you should just be able to copy config from the git archive to that location.

Or it may be that it's missing the line zfsmanager_conf=/etc/webmin/zfsmanager/config from that file, in which case you can run`echo "zfsmanager_conf=/etc/webmin/zfsmanager/config" >> /etc/webmin/zfsmanager/config` or `echo "zfsmanager_conf=/etc/webmin/zfsmanager/config" | sudo tee --append  /etc/webmin/zfsmanager/config`

**Comment by mcwago** [comment]
it works, great, thx

**Comment by jonmatifa** [comment]
Fixed on commit 50b825e
